name: fl_bases_web
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_storage: ^2.1.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  riverpod_annotation: ^2.6.1
  universal_html: ^2.2.4
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svg/
